homework 6
zulteg/python-course-alphabet pull request #5
Opened 2019-05-11 11:13 UTC by zulteg

2019-05-18 19:09 UTC, yuriimchg requested changes
привіт
перевірив дз
все дуже круто
залишив коментарі, що, на мою думку, можна було б покращити
але, оскільки в завданні не говориться про це, то залишаю це на твій розсуд
також, оскільки є декілька запитань, то ще не кидаю дз в done

2019-05-18 19:09 UTC, yuriimchg commented on oop/homework.py
> +        self._saturation_level -= value
це можна оформити трохи гарніше через вбудований метод `max()`

2019-05-18 19:09 UTC, yuriimchg commented on oop/homework.py
> +        if self._saturation_level > 100:
і це, відповідно, через `min()`

2019-05-18 19:09 UTC, yuriimchg commented on oop/homework.py
> +            raise ValueError("Sorry there is only two types of roofs")
я, як користувач, не знатиму, які бувають типи даху, тому бажано було би вказувати ще їх в ексепшні

2019-05-18 19:09 UTC, yuriimchg commented on oop/homework.py
> +            raise ValueError("Sorry we don't have such material")
тут також варто вказати, які є типи матеріалів

2019-05-18 19:09 UTC, yuriimchg commented on oop/homework.py
> +            elif message_type == 2:
а для чого параметр `message_type`?

2019-05-18 19:09 UTC, yuriimchg commented on oop/homework.py
> +    def validate_params(width: float, height: float, message_type=1):
ти впевнений, що тут треба використовувати `@staticmethod`?

2019-05-19 08:26 UTC, zulteg commented on oop/homework.py
> +        self._saturation_level -= value
согласен, отличная идея

2019-05-19 08:26 UTC, zulteg commented on oop/homework.py
> +        if self._saturation_level > 100:
+

2019-05-19 08:26 UTC, zulteg commented on oop/homework.py
> +        if self._saturation_level > 100:
+

2019-05-19 08:40 UTC, zulteg commented on oop/homework.py
> +    def validate_params(width: float, height: float, message_type=1):
скорее нет, лучше вынесу этот метод в отдельную функцию

2019-05-19 08:41 UTC, zulteg commented on oop/homework.py
> +            elif message_type == 2:
в условиях задачи на разные проверки должен выводится разный текст, решил сделать через отдельную переменную

2019-05-19 09:35 UTC, yuriimchg submitted a review, later dismissed
перевірив, все ок,
в деяких місцях краще лишити, як раніше для кращої читабельності

2019-05-19 09:35 UTC, yuriimchg commented on oop/homework.py
> -      Than if your cat run more or eq than 25 _reduce_saturation_level with value 2
до речі, докстрінги не обов'язково обмежувати до довжини 79

2019-05-19 09:35 UTC, yuriimchg commented on oop/homework.py
> +        return sum([
до речі, тут падає читабельність, коли це все розбити на декілька рядків
тому краще лишити, як було

2019-05-19 09:55 UTC, zulteg commented on oop/homework.py
> +        return sum([
понял, переносить не во вред читаемости

2019-05-19 10:59 UTC, merged