homework 8 - tests
zulteg/python-course-alphabet pull request #8
Opened 2019-06-11 11:42 UTC by zulteg

2019-06-15 11:29 UTC, yuriimchg requested changes
привіт
є декілька нюансів з дз, але загалом все добре

2019-06-15 11:29 UTC, yuriimchg commented on tests_homework/tests.py
> +from tests_homework.models import InvalidValueException, Cesar, Garage, Car
в тебе імпорти викликаються з кореневої папки апплікації, а ` test_json_serialize` - з папки з тестовим дз;
так не має бути

2019-06-15 11:29 UTC, yuriimchg commented on tests_homework/tests.py
> +from tests_homework.models import InvalidValueException, Cesar, Garage, Car
в мене падають 3 тести через ці помилки з імпортами

2019-06-15 11:29 UTC, yuriimchg commented on tests_homework/tests.py
> +        self.assertEqual(car1, car2)
не дуже добре, коли одним тестом покривається декілька випадків. Краще нехай один тест перевіряє, чи машини співпадають, а інший - чи не співпадають

2019-06-18 14:54 UTC, zulteg commented on tests_homework/tests.py
> +        self.assertEqual(car1, car2)
хмм, прост проверяется как раз один метод класса `__eq__` 
я разделил equal / not equal

2019-06-18 14:54 UTC, zulteg commented on tests_homework/tests.py
> +from tests_homework.models import InvalidValueException, Cesar, Garage, Car
да, не обратил внимание, запускал с пичарма

2019-06-18 15:58 UTC, yuriimchg commented on tests_homework/tests.py
> +        self.assertEqual(car1, car2)
краще розділяти на різні тести

бо в тебе один тест перевіряє метод `==`, різні ціни, різні типи, різних виробників і різні номери. Це все різні тесткейси

2019-06-18 16:03 UTC, zulteg commented on tests_homework/tests.py
> +        self.assertEqual(car1, car2)
т.е разделить еще каждый assertNotEqual на отдельный тест?

2019-06-18 16:05 UTC, yuriimchg commented on tests_homework/tests.py
> +        self.assertEqual(car1, car2)
так

2019-06-18 16:17 UTC, zulteg commented on tests_homework/tests.py
> +        self.assertEqual(car1, car2)
ага, сделал

2019-06-19 18:07 UTC, yuriimchg approved these changes
:+1:

2019-06-20 08:39 UTC, merged